-- Explicit Lazy Jane's menu composition data.
--
-- This is service-facing composition, not a kitchen recipe. It is sourced from
-- the supplied menu names/descriptions plus the explicit choices already
-- modeled in the diner flow. The function is reusable so a fresh database can
-- run migrations before the base menu seed and attach the composition after
-- the 427 menu items are inserted.

CREATE OR REPLACE FUNCTION seed_lazy_janes_menu_composition()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  CREATE TEMP TABLE seed_ingredient_facts (
    ingredient_name text PRIMARY KEY,
    allergen_flags text[] NOT NULL DEFAULT '{}',
    sort_order integer NOT NULL
  ) ON COMMIT DROP;

  INSERT INTO seed_ingredient_facts (
    ingredient_name,
    allergen_flags,
    sort_order
  )
  VALUES
    ('Almonds', ARRAY['tree_nut']::text[], 10),
    ('American Cheese', ARRAY['milk']::text[], 20),
    ('Apple', ARRAY[]::text[], 30),
    ('Applesauce', ARRAY[]::text[], 40),
    ('Artichoke Hearts', ARRAY[]::text[], 50),
    ('Arugula', ARRAY[]::text[], 60),
    ('Avocado', ARRAY[]::text[], 70),
    ('BBQ Sauce', ARRAY[]::text[], 80),
    ('Bacon', ARRAY[]::text[], 90),
    ('Bagel', ARRAY['wheat']::text[], 100),
    ('Balsamic', ARRAY[]::text[], 110),
    ('Balsamic Glaze', ARRAY[]::text[], 120),
    ('Balsamic Vinaigrette', ARRAY[]::text[], 130),
    ('Barley', ARRAY['wheat']::text[], 140),
    ('Bermuda Onion', ARRAY[]::text[], 150),
    ('Black Beans', ARRAY[]::text[], 160),
    ('Black Olive Dressing', ARRAY[]::text[], 170),
    ('Blackened Chicken', ARRAY[]::text[], 180),
    ('Blackened Salmon', ARRAY['fish']::text[], 190),
    ('Blue Cheese', ARRAY['milk']::text[], 200),
    ('Blueberries', ARRAY[]::text[], 210),
    ('Broccoli', ARRAY[]::text[], 220),
    ('Brown Onions', ARRAY[]::text[], 230),
    ('Buffalo Chicken', ARRAY[]::text[], 240),
    ('Buffalo Sauce', ARRAY[]::text[], 250),
    ('Bun', ARRAY['wheat']::text[], 260),
    ('Burger Patty', ARRAY[]::text[], 270),
    ('Butter', ARRAY['milk']::text[], 280),
    ('Carrots', ARRAY[]::text[], 290),
    ('Cashews', ARRAY['tree_nut']::text[], 300),
    ('Cheddar', ARRAY['milk']::text[], 310),
    ('Cheese', ARRAY['milk']::text[], 320),
    ('Chicken', ARRAY[]::text[], 330),
    ('Chicken Burger', ARRAY[]::text[], 340),
    ('Chicken Liver', ARRAY[]::text[], 350),
    ('Chicken Meatloaf', ARRAY[]::text[], 360),
    ('Chickpeas', ARRAY[]::text[], 370),
    ('Chipotle Mayo', ARRAY[]::text[], 380),
    ('Chocolate', ARRAY['milk']::text[], 390),
    ('Chopped Liver', ARRAY[]::text[], 400),
    ('Cilantro', ARRAY[]::text[], 410),
    ('Cilantro Lime Vinaigrette', ARRAY[]::text[], 420),
    ('Cinnamon Sugar', ARRAY[]::text[], 430),
    ('Clams', ARRAY['shellfish']::text[], 440),
    ('Cole Slaw', ARRAY[]::text[], 450),
    ('Corn', ARRAY[]::text[], 460),
    ('Corned Beef', ARRAY[]::text[], 470),
    ('Cottage Cheese', ARRAY['milk']::text[], 480),
    ('Crab Cake', ARRAY['shellfish']::text[], 490),
    ('Cranberry Sauce', ARRAY[]::text[], 500),
    ('Cream Cheese', ARRAY['milk']::text[], 510),
    ('Creamy Italian Dressing', ARRAY[]::text[], 520),
    ('Cucumber', ARRAY[]::text[], 530),
    ('Decaf Coffee', ARRAY[]::text[], 540),
    ('Dijon Mustard', ARRAY[]::text[], 550),
    ('Dressing', ARRAY[]::text[], 560),
    ('Egg', ARRAY['egg']::text[], 570),
    ('Feta', ARRAY['milk']::text[], 580),
    ('Flounder', ARRAY['fish']::text[], 590),
    ('Focaccia Bread', ARRAY['wheat']::text[], 600),
    ('French Fries', ARRAY[]::text[], 610),
    ('Fresh Mozzarella', ARRAY['milk']::text[], 620),
    ('Fresh Mushrooms', ARRAY[]::text[], 630),
    ('Fresh Vegetables', ARRAY[]::text[], 640),
    ('Fried Chicken', ARRAY[]::text[], 650),
    ('Fried Noodles', ARRAY['wheat']::text[], 660),
    ('Fried Onions', ARRAY[]::text[], 670),
    ('Fried String Onions', ARRAY[]::text[], 680),
    ('Garlic & Olive Oil', ARRAY[]::text[], 690),
    ('Garlic Bread', ARRAY['wheat']::text[], 700),
    ('Garlic Mashed Potatoes', ARRAY[]::text[], 710),
    ('Goat Cheese', ARRAY['milk']::text[], 720),
    ('Gravy', ARRAY[]::text[], 730),
    ('Green Apple', ARRAY[]::text[], 740),
    ('Green Peppers', ARRAY[]::text[], 750),
    ('Grilled Cheese', ARRAY['milk', 'wheat']::text[], 760),
    ('Grilled Chicken', ARRAY[]::text[], 770),
    ('Guacamole', ARRAY[]::text[], 780),
    ('Ham', ARRAY[]::text[], 790),
    ('Hard Roll', ARRAY['wheat']::text[], 800),
    ('Home Fries', ARRAY[]::text[], 810),
    ('Honey', ARRAY[]::text[], 820),
    ('Honey Balsamic Dressing', ARRAY[]::text[], 830),
    ('Honey Mustard', ARRAY[]::text[], 840),
    ('Iceberg Lettuce', ARRAY[]::text[], 850),
    ('Jalapeño Peppers', ARRAY[]::text[], 860),
    ('Jello', ARRAY[]::text[], 870),
    ('Jelly', ARRAY[]::text[], 880),
    ('Lean Beef Patty', ARRAY[]::text[], 890),
    ('Lemon Garlic Dressing', ARRAY[]::text[], 900),
    ('Lemon Vinaigrette', ARRAY[]::text[], 910),
    ('Lettuce', ARRAY[]::text[], 920),
    ('Lime Juice', ARRAY[]::text[], 930),
    ('Mandarin Oranges', ARRAY[]::text[], 940),
    ('Mango', ARRAY[]::text[], 950),
    ('Marinara Sauce', ARRAY[]::text[], 960),
    ('Marinated Chicken', ARRAY[]::text[], 970),
    ('Mayo', ARRAY['egg']::text[], 980),
    ('Mesclun', ARRAY[]::text[], 990),
    ('Milk', ARRAY['milk']::text[], 1000),
    ('Mixed Greens', ARRAY[]::text[], 1010),
    ('Monterey Jack', ARRAY['milk']::text[], 1020),
    ('Mozzarella', ARRAY['milk']::text[], 1030),
    ('Mushrooms', ARRAY[]::text[], 1040),
    ('Noodles', ARRAY['wheat']::text[], 1050),
    ('Nova', ARRAY['fish']::text[], 1060),
    ('Olive Oil', ARRAY[]::text[], 1070),
    ('Olives', ARRAY[]::text[], 1080),
    ('Onion', ARRAY[]::text[], 1090),
    ('Pasta', ARRAY['wheat']::text[], 1100),
    ('Pastrami', ARRAY[]::text[], 1110),
    ('Peanut Butter & Jelly', ARRAY['peanut', 'wheat']::text[], 1120),
    ('Pears', ARRAY[]::text[], 1130),
    ('Peppers', ARRAY[]::text[], 1140),
    ('Pesto Sauce', ARRAY[]::text[], 1150),
    ('Pickles', ARRAY[]::text[], 1160),
    ('Pineapple', ARRAY[]::text[], 1170),
    ('Pita', ARRAY['wheat']::text[], 1180),
    ('Poached Pears', ARRAY[]::text[], 1190),
    ('Poppy White Wine Vinaigrette', ARRAY[]::text[], 1200),
    ('Pork Sausage', ARRAY[]::text[], 1210),
    ('Portabella Mushrooms', ARRAY[]::text[], 1220),
    ('Potato Pancake', ARRAY[]::text[], 1230),
    ('Potato Salad', ARRAY['egg']::text[], 1240),
    ('Potatoes', ARRAY[]::text[], 1250),
    ('Provolone', ARRAY['milk']::text[], 1260),
    ('Quinoa', ARRAY[]::text[], 1270),
    ('Raisins', ARRAY[]::text[], 1280),
    ('Ranch Dressing', ARRAY[]::text[], 1290),
    ('Raspberry Vinaigrette', ARRAY[]::text[], 1300),
    ('Red Beans', ARRAY[]::text[], 1310),
    ('Red Onion', ARRAY[]::text[], 1320),
    ('Red Peppers', ARRAY[]::text[], 1330),
    ('Regular Coffee', ARRAY[]::text[], 1340),
    ('Rice', ARRAY[]::text[], 1350),
    ('Roast Beef', ARRAY[]::text[], 1360),
    ('Roast Turkey', ARRAY[]::text[], 1370),
    ('Roasted Peppers', ARRAY[]::text[], 1380),
    ('Romaine Lettuce', ARRAY[]::text[], 1390),
    ('Russian Dressing', ARRAY[]::text[], 1400),
    ('Salami', ARRAY[]::text[], 1410),
    ('Salmon', ARRAY['fish']::text[], 1420),
    ('Salsa', ARRAY[]::text[], 1430),
    ('Sauerkraut', ARRAY[]::text[], 1440),
    ('Sausage', ARRAY[]::text[], 1450),
    ('Sautéed Onions', ARRAY[]::text[], 1460),
    ('Scallions', ARRAY[]::text[], 1470),
    ('Scallops', ARRAY['shellfish']::text[], 1480),
    ('Sesame Chicken', ARRAY['sesame']::text[], 1490),
    ('Sesame Seeds', ARRAY['sesame']::text[], 1500),
    ('Shrimp', ARRAY['shellfish']::text[], 1510),
    ('Skim Milk', ARRAY['milk']::text[], 1520),
    ('Skirt Steak', ARRAY[]::text[], 1530),
    ('Snow Peas', ARRAY[]::text[], 1540),
    ('Sour Cream', ARRAY['milk']::text[], 1550),
    ('Soy Sauce', ARRAY['soy']::text[], 1560),
    ('Spaghetti', ARRAY['wheat']::text[], 1570),
    ('Spinach', ARRAY[]::text[], 1580),
    ('Steak', ARRAY[]::text[], 1590),
    ('Strawberries', ARRAY[]::text[], 1600),
    ('Strawberry', ARRAY['milk']::text[], 1610),
    ('String Beans', ARRAY[]::text[], 1620),
    ('Stuffing', ARRAY[]::text[], 1630),
    ('Sun-Dried Cranberries', ARRAY[]::text[], 1640),
    ('Sun-Dried Tomatoes', ARRAY[]::text[], 1650),
    ('Swiss Cheese', ARRAY['milk']::text[], 1660),
    ('Swordfish', ARRAY['fish']::text[], 1670),
    ('Tartar Sauce', ARRAY[]::text[], 1680),
    ('Taylor Ham', ARRAY[]::text[], 1690),
    ('Teriyaki Dressing', ARRAY[]::text[], 1700),
    ('Teriyaki Sauce', ARRAY[]::text[], 1710),
    ('Toast', ARRAY['wheat']::text[], 1720),
    ('Tomato', ARRAY[]::text[], 1730),
    ('Torpedo Roll', ARRAY['wheat']::text[], 1740),
    ('Tortilla Chips', ARRAY[]::text[], 1750),
    ('Tortilla Shell', ARRAY[]::text[], 1760),
    ('Tuna', ARRAY['fish']::text[], 1770),
    ('Turkey', ARRAY[]::text[], 1780),
    ('Turkey Burger', ARRAY[]::text[], 1790),
    ('Turkey Meatloaf', ARRAY[]::text[], 1800),
    ('Turkey Patty', ARRAY[]::text[], 1810),
    ('Turkey Sausage', ARRAY[]::text[], 1820),
    ('Tzatziki Sauce', ARRAY[]::text[], 1830),
    ('Vanilla', ARRAY['milk']::text[], 1840),
    ('Vegetables', ARRAY[]::text[], 1850),
    ('Vodka Sauce', ARRAY[]::text[], 1860),
    ('Walnuts', ARRAY['tree_nut']::text[], 1870),
    ('White Balsamic Dressing', ARRAY[]::text[], 1880),
    ('White Beans', ARRAY[]::text[], 1890),
    ('Zucchini', ARRAY[]::text[], 1900),
    ('Pepperoni', ARRAY[]::text[], 1910),
    ('Olive Oil & Lemon Dressing', ARRAY[]::text[], 1920),
    ('Cherry Tomatoes', ARRAY[]::text[], 1930),
    ('Chili', ARRAY[]::text[], 1940),
    ('Pico de Gallo', ARRAY[]::text[], 1950),
    ('Garlic', ARRAY[]::text[], 1960),
    ('Lemon Wedge', ARRAY[]::text[], 1970),
    ('Garlic White Wine Sauce', ARRAY[]::text[], 1980),
    ('Matzoh Balls', ARRAY['wheat', 'egg']::text[], 1990),
    ('Balsamic Dressing', ARRAY[]::text[], 2000),
    ('Tossed Salad', ARRAY[]::text[], 2010),
    ('Veggie Burger', ARRAY[]::text[], 2020),
    ('Horseradish', ARRAY[]::text[], 2030);

  INSERT INTO ingredients (
    name,
    allergen_flags,
    sort_order
  )
  SELECT
    ingredient_name,
    allergen_flags,
    sort_order
  FROM seed_ingredient_facts
  ON CONFLICT ((lower(name))) DO UPDATE
  SET
    allergen_flags = EXCLUDED.allergen_flags,
    sort_order = LEAST(ingredients.sort_order, EXCLUDED.sort_order),
    is_active = true,
    updated_at = now();


  CREATE TEMP TABLE seed_menu_components (
    group_name text NOT NULL,
    category_name text NOT NULL,
    item_name text NOT NULL,
    ingredient_name text NOT NULL,
    can_remove boolean NOT NULL,
    can_extra boolean NOT NULL,
    extra_price numeric(10, 2) NOT NULL,
    sort_order integer NOT NULL
  ) ON COMMIT DROP;

  INSERT INTO seed_menu_components (
    group_name,
    category_name,
    item_name,
    ingredient_name,
    can_remove,
    can_extra,
    extra_price,
    sort_order
  )
  VALUES
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'Drunken Chicken', 'Fresh Mozzarella', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'Drunken Chicken', 'Vodka Sauce', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'Buffalo Cheese', 'Lettuce', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'Buffalo Cheese', 'Cheddar', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'Buffalo Cheese', 'Buffalo Sauce', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'BLT Ranch', 'Bacon', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'BLT Ranch', 'Lettuce', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'BLT Ranch', 'Tomato', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'BLT Ranch', 'American Cheese', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'BLT Ranch', 'Ranch Dressing', true, true, 0.00, 50),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'The Pesto', 'Fresh Mozzarella', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'The Pesto', 'Pesto Sauce', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'The Pesto', 'Sun-Dried Tomatoes', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'The Caprese', 'Roasted Peppers', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'The Caprese', 'Arugula', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'The Caprese', 'Fresh Mozzarella', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'The Caprese', 'Balsamic Glaze', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'The David', 'Fresh Mozzarella', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'The David', 'Olive Oil', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'The David', 'Pepperoni', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'The Arizona', 'Jalapeño Peppers', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'The Arizona', 'Red Onion', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'The Arizona', 'Lettuce', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Chicken Cutlet Sandwiches', 'The Arizona', 'Chipotle Mayo', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Fried Chicken Sandwiches', 'The Ritz', 'Red Onion', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Fried Chicken Sandwiches', 'The Ritz', 'Lettuce', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Fried Chicken Sandwiches', 'The Ritz', 'Avocado', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Fried Chicken Sandwiches', 'The Ritz', 'Pickles', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Fried Chicken Sandwiches', 'The Ritz', 'Chipotle Mayo', true, true, 0.00, 50),
    ('Sandwiches & Deli', 'Fried Chicken Sandwiches', 'The Texan', 'Bacon', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Fried Chicken Sandwiches', 'The Texan', 'Fried String Onions', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Fried Chicken Sandwiches', 'The Texan', 'Cheddar', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Fried Chicken Sandwiches', 'The Texan', 'BBQ Sauce', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Fried Chicken Sandwiches', 'The Italian', 'Mozzarella', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Fried Chicken Sandwiches', 'The Italian', 'Marinara Sauce', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Fried Chicken Sandwiches', 'The Monte', 'Ham', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Fried Chicken Sandwiches', 'The Monte', 'Swiss Cheese', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Fried Chicken Sandwiches', 'The Monte', 'Honey Mustard', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Fried Chicken Sandwiches', 'The Club', 'Bacon', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Fried Chicken Sandwiches', 'The Club', 'Lettuce', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Fried Chicken Sandwiches', 'The Club', 'Tomato', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Fried Chicken Sandwiches', 'The Club', 'Mayo', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Wraps', 'Buffalo Chicken Wrap', 'Grilled Chicken', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Wraps', 'Buffalo Chicken Wrap', 'Romaine Lettuce', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Wraps', 'Buffalo Chicken Wrap', 'Tomato', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Wraps', 'Buffalo Chicken Wrap', 'Blue Cheese', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Wraps', 'Buffalo Chicken Wrap', 'Buffalo Sauce', true, true, 0.00, 50),
    ('Sandwiches & Deli', 'Wraps', 'Philly Cheesesteak Wrap', 'Sautéed Onions', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Wraps', 'Blackened Chicken Wrap', 'Tomato', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Wraps', 'Blackened Chicken Wrap', 'Avocado', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Wraps', 'Blackened Chicken Wrap', 'Black Beans', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Wraps', 'Turkey Wrap Special', 'Lettuce', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Wraps', 'Turkey Wrap Special', 'Avocado', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Wraps', 'Turkey Wrap Special', 'Goat Cheese', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Wraps', 'Turkey Wrap Special', 'Honey Mustard', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Wraps', 'BBQ Beef Wrap', 'Roast Beef', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Wraps', 'BBQ Beef Wrap', 'Fried Onions', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Wraps', 'BBQ Beef Wrap', 'Mozzarella', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Wraps', 'Gyro Wrap', 'Lettuce', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Wraps', 'Gyro Wrap', 'Tomato', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Wraps', 'Gyro Wrap', 'Avocado', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Wraps', 'Gyro Wrap', 'Creamy Italian Dressing', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Wraps', 'Tex Mex Wrap', 'Grilled Chicken', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Wraps', 'Tex Mex Wrap', 'Tomato', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Wraps', 'Tex Mex Wrap', 'Avocado', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Wraps', 'Tex Mex Wrap', 'Black Beans', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Wraps', 'Tex Mex Wrap', 'Monterey Jack', true, true, 0.00, 50),
    ('Sandwiches & Deli', 'Wraps', 'Tex Mex Wrap', 'Sour Cream', true, true, 0.00, 60),
    ('Sandwiches & Deli', 'Wraps', 'Grilled Chicken Pesto Wrap', 'Roasted Peppers', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Wraps', 'Grilled Chicken Pesto Wrap', 'Red Onion', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Wraps', 'Grilled Chicken Pesto Wrap', 'Tomato', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Wraps', 'Grilled Chicken Pesto Wrap', 'Pesto Sauce', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Lemon Shrimp Salad', 'Shrimp', true, true, 0.00, 10),
    ('Specials', 'Specials', 'Lemon Shrimp Salad', 'Roasted Peppers', true, true, 0.00, 20),
    ('Specials', 'Specials', 'Lemon Shrimp Salad', 'Bacon', true, true, 0.00, 30),
    ('Specials', 'Specials', 'Lemon Shrimp Salad', 'Red Onion', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Lemon Shrimp Salad', 'String Beans', true, true, 0.00, 50),
    ('Specials', 'Specials', 'Lemon Shrimp Salad', 'Tomato', true, true, 0.00, 60),
    ('Specials', 'Specials', 'Lemon Shrimp Salad', 'Mesclun', true, true, 0.00, 70),
    ('Specials', 'Specials', 'Lemon Shrimp Salad', 'Scallions', true, true, 0.00, 80),
    ('Specials', 'Specials', 'Lemon Shrimp Salad', 'Lemon Garlic Dressing', true, true, 0.00, 90),
    ('Specials', 'Specials', 'Marion’s Chopped Salad', 'Sesame Chicken', true, true, 0.00, 10),
    ('Specials', 'Specials', 'Marion’s Chopped Salad', 'Portabella Mushrooms', true, true, 0.00, 20),
    ('Specials', 'Specials', 'Marion’s Chopped Salad', 'Iceberg Lettuce', true, true, 0.00, 30),
    ('Specials', 'Specials', 'Marion’s Chopped Salad', 'Carrots', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Marion’s Chopped Salad', 'Cucumber', true, true, 0.00, 50),
    ('Specials', 'Specials', 'Marion’s Chopped Salad', 'Fresh Mozzarella', true, true, 0.00, 60),
    ('Specials', 'Specials', 'Marion’s Chopped Salad', 'Almonds', true, true, 0.00, 70),
    ('Specials', 'Specials', 'Marion’s Chopped Salad', 'Black Olive Dressing', true, true, 0.00, 80),
    ('Specials', 'Specials', 'South Beach Salad with Grilled Chicken', 'Grilled Chicken', true, true, 0.00, 10),
    ('Specials', 'Specials', 'South Beach Salad with Grilled Chicken', 'Spinach', true, true, 0.00, 20),
    ('Specials', 'Specials', 'South Beach Salad with Grilled Chicken', 'Goat Cheese', true, true, 0.00, 30),
    ('Specials', 'Specials', 'South Beach Salad with Grilled Chicken', 'Sun-Dried Cranberries', true, true, 0.00, 40),
    ('Specials', 'Specials', 'South Beach Salad with Grilled Chicken', 'Avocado', true, true, 0.00, 50),
    ('Specials', 'Specials', 'South Beach Salad with Grilled Chicken', 'Red Onion', true, true, 0.00, 60),
    ('Specials', 'Specials', 'South Beach Salad with Grilled Chicken', 'Tomato', true, true, 0.00, 70),
    ('Specials', 'Specials', 'South Beach Salad with Grilled Chicken', 'White Balsamic Dressing', true, true, 0.00, 80),
    ('Specials', 'Specials', 'Insalata Italiano', 'Grilled Chicken', true, true, 0.00, 10),
    ('Specials', 'Specials', 'Insalata Italiano', 'Fresh Mozzarella', true, true, 0.00, 20),
    ('Specials', 'Specials', 'Insalata Italiano', 'Roasted Peppers', true, true, 0.00, 30),
    ('Specials', 'Specials', 'Insalata Italiano', 'Artichoke Hearts', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Insalata Italiano', 'Tomato', true, true, 0.00, 50),
    ('Specials', 'Specials', 'Insalata Italiano', 'Olive Oil & Lemon Dressing', true, true, 0.00, 60),
    ('Specials', 'Specials', 'Paulo’s Salad with Grilled Chicken', 'Grilled Chicken', true, true, 0.00, 10),
    ('Specials', 'Specials', 'Paulo’s Salad with Grilled Chicken', 'Poached Pears', true, true, 0.00, 20),
    ('Specials', 'Specials', 'Paulo’s Salad with Grilled Chicken', 'Walnuts', true, true, 0.00, 30),
    ('Specials', 'Specials', 'Paulo’s Salad with Grilled Chicken', 'Raisins', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Paulo’s Salad with Grilled Chicken', 'Mixed Greens', true, true, 0.00, 50),
    ('Specials', 'Specials', 'Paulo’s Salad with Grilled Chicken', 'Raspberry Vinaigrette', true, true, 0.00, 60),
    ('Specials', 'Specials', 'Teriyaki Chicken Salad', 'Marinated Chicken', true, true, 0.00, 10),
    ('Specials', 'Specials', 'Teriyaki Chicken Salad', 'Walnuts', true, true, 0.00, 20),
    ('Specials', 'Specials', 'Teriyaki Chicken Salad', 'Mandarin Oranges', true, true, 0.00, 30),
    ('Specials', 'Specials', 'Teriyaki Chicken Salad', 'Snow Peas', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Teriyaki Chicken Salad', 'Mixed Greens', true, true, 0.00, 50),
    ('Specials', 'Specials', 'Teriyaki Chicken Salad', 'Fried Noodles', true, true, 0.00, 60),
    ('Specials', 'Specials', 'Teriyaki Chicken Salad', 'Teriyaki Dressing', true, true, 0.00, 70),
    ('Specials', 'Specials', 'Focaccia Sandwich', 'Grilled Chicken', true, true, 0.00, 10),
    ('Specials', 'Specials', 'Focaccia Sandwich', 'Roasted Peppers', true, true, 0.00, 20),
    ('Specials', 'Specials', 'Focaccia Sandwich', 'Fresh Mozzarella', true, true, 0.00, 30),
    ('Specials', 'Specials', 'Focaccia Sandwich', 'Pesto Sauce', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Avocado Tuna Salad', 'Tuna', true, true, 0.00, 10),
    ('Specials', 'Specials', 'Avocado Tuna Salad', 'Avocado', true, true, 0.00, 20),
    ('Specials', 'Specials', 'Avocado Tuna Salad', 'Cucumber', true, true, 0.00, 30),
    ('Specials', 'Specials', 'Avocado Tuna Salad', 'Red Onion', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Avocado Tuna Salad', 'Cilantro', true, true, 0.00, 50),
    ('Specials', 'Specials', 'Avocado Tuna Salad', 'Lemon Vinaigrette', true, true, 0.00, 60),
    ('Specials', 'Specials', 'Strawberry Spinach Salad', 'Spinach', true, true, 0.00, 10),
    ('Specials', 'Specials', 'Strawberry Spinach Salad', 'Strawberries', true, true, 0.00, 20),
    ('Specials', 'Specials', 'Strawberry Spinach Salad', 'Sesame Seeds', true, true, 0.00, 30),
    ('Specials', 'Specials', 'Strawberry Spinach Salad', 'Poppy White Wine Vinaigrette', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Coconut Chicken Ala Ritz', 'Chicken', true, true, 0.00, 10),
    ('Specials', 'Specials', 'Coconut Chicken Ala Ritz', 'Pears', true, true, 0.00, 20),
    ('Specials', 'Specials', 'Coconut Chicken Ala Ritz', 'Sun-Dried Cranberries', true, true, 0.00, 30),
    ('Specials', 'Specials', 'Coconut Chicken Ala Ritz', 'Green Apple', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Coconut Chicken Ala Ritz', 'Walnuts', true, true, 0.00, 50),
    ('Specials', 'Specials', 'Coconut Chicken Ala Ritz', 'White Balsamic Dressing', true, true, 0.00, 60),
    ('Specials', 'Specials', 'String Bean Salad with Grilled Chicken', 'String Beans', true, true, 0.00, 10),
    ('Specials', 'Specials', 'String Bean Salad with Grilled Chicken', 'Grilled Chicken', true, true, 0.00, 20),
    ('Specials', 'Specials', 'String Bean Salad with Grilled Chicken', 'Tomato', true, true, 0.00, 30),
    ('Specials', 'Specials', 'String Bean Salad with Grilled Chicken', 'Fresh Mozzarella', true, true, 0.00, 40),
    ('Specials', 'Specials', 'String Bean Salad with Grilled Chicken', 'Red Onion', true, true, 0.00, 50),
    ('Specials', 'Specials', 'String Bean Salad with Grilled Chicken', 'Honey Balsamic Dressing', true, true, 0.00, 60),
    ('Specials', 'Specials', 'Southwest Cobb Salad', 'Blackened Chicken', true, true, 0.00, 10),
    ('Specials', 'Specials', 'Southwest Cobb Salad', 'Iceberg Lettuce', true, true, 0.00, 20),
    ('Specials', 'Specials', 'Southwest Cobb Salad', 'Cilantro', true, true, 0.00, 30),
    ('Specials', 'Specials', 'Southwest Cobb Salad', 'Corn', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Southwest Cobb Salad', 'Black Beans', true, true, 0.00, 50),
    ('Specials', 'Specials', 'Southwest Cobb Salad', 'Red Peppers', true, true, 0.00, 60),
    ('Specials', 'Specials', 'Southwest Cobb Salad', 'Monterey Jack', true, true, 0.00, 70),
    ('Specials', 'Specials', 'Southwest Cobb Salad', 'Cheddar', true, true, 0.00, 80),
    ('Specials', 'Specials', 'Mango Barley Chicken Salad', 'Red Peppers', true, true, 0.00, 10),
    ('Specials', 'Specials', 'Mango Barley Chicken Salad', 'Green Peppers', true, true, 0.00, 20),
    ('Specials', 'Specials', 'Mango Barley Chicken Salad', 'Red Onion', true, true, 0.00, 30),
    ('Specials', 'Specials', 'Mango Barley Chicken Salad', 'Mango', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Mango Barley Chicken Salad', 'Barley', true, true, 0.00, 50),
    ('Specials', 'Specials', 'Mango Barley Chicken Salad', 'Lime Juice', true, true, 0.00, 60),
    ('Specials', 'Specials', 'Mango Barley Chicken Salad', 'Olive Oil', true, true, 0.00, 70),
    ('Specials', 'Specials', 'Mango Barley Chicken Salad', 'Cilantro', true, true, 0.00, 80),
    ('Specials', 'Specials', 'Mango Barley Chicken Salad', 'Honey', true, true, 0.00, 90),
    ('Specials', 'Specials', 'Mango Barley Chicken Salad', 'Dijon Mustard', true, true, 0.00, 100),
    ('Specials', 'Specials', 'Pan Fried Crab Cake Sandwich', 'Crab Cake', true, true, 0.00, 10),
    ('Specials', 'Specials', 'Pan Fried Crab Cake Sandwich', 'Roasted Peppers', true, true, 0.00, 20),
    ('Specials', 'Specials', 'Pan Fried Crab Cake Sandwich', 'Avocado', true, true, 0.00, 30),
    ('Specials', 'Specials', 'Pan Fried Crab Cake Sandwich', 'Lettuce', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Pan Fried Crab Cake Sandwich', 'Tartar Sauce', true, true, 0.00, 50),
    ('Specials', 'Specials', 'Focaccia Special', 'Grilled Chicken', true, true, 0.00, 10),
    ('Specials', 'Specials', 'Focaccia Special', 'Roasted Peppers', true, true, 0.00, 20),
    ('Specials', 'Specials', 'Focaccia Special', 'Fresh Mozzarella', true, true, 0.00, 30),
    ('Specials', 'Specials', 'Focaccia Special', 'Pesto Sauce', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Teriyaki Chicken Sub', 'Grilled Chicken', true, true, 0.00, 10),
    ('Specials', 'Specials', 'Teriyaki Chicken Sub', 'Teriyaki Sauce', true, true, 0.00, 20),
    ('Specials', 'Specials', 'Teriyaki Chicken Sub', 'Lettuce', true, true, 0.00, 30),
    ('Specials', 'Specials', 'Teriyaki Chicken Sub', 'Tomato', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Teriyaki Chicken Sub', 'Avocado', true, true, 0.00, 50),
    ('Specials', 'Specials', 'Montreal Chicken Quinoa Salad', 'Grilled Chicken', true, true, 0.00, 10),
    ('Specials', 'Specials', 'Montreal Chicken Quinoa Salad', 'Quinoa', true, true, 0.00, 20),
    ('Specials', 'Specials', 'Montreal Chicken Quinoa Salad', 'Zucchini', true, true, 0.00, 30),
    ('Specials', 'Specials', 'Montreal Chicken Quinoa Salad', 'Tomato', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Montreal Chicken Quinoa Salad', 'Cucumber', true, true, 0.00, 50),
    ('Specials', 'Specials', 'Montreal Chicken Quinoa Salad', 'Carrots', true, true, 0.00, 60),
    ('Specials', 'Specials', 'Montreal Chicken Quinoa Salad', 'Mixed Greens', true, true, 0.00, 70),
    ('Specials', 'Specials', 'Montreal Chicken Quinoa Salad', 'Chickpeas', true, true, 0.00, 80),
    ('Specials', 'Specials', 'Montreal Chicken Quinoa Salad', 'Lemon Vinaigrette', true, true, 0.00, 90),
    ('Specials', 'Specials', 'Chopped Burger Salad', 'Burger Patty', true, true, 0.00, 10),
    ('Specials', 'Specials', 'Chopped Burger Salad', 'Tomato', true, true, 0.00, 20),
    ('Specials', 'Specials', 'Chopped Burger Salad', 'Red Onion', true, true, 0.00, 30),
    ('Specials', 'Specials', 'Chopped Burger Salad', 'Cucumber', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Chopped Burger Salad', 'Lettuce', true, true, 0.00, 50),
    ('Specials', 'Specials', 'Chopped Burger Salad', 'Monterey Jack', true, true, 0.00, 60),
    ('Specials', 'Specials', 'Chopped Burger Salad', 'Pickles', true, true, 0.00, 70),
    ('Specials', 'Specials', 'Crispy Buffalo Chicken Salad', 'Buffalo Chicken', true, true, 0.00, 10),
    ('Specials', 'Specials', 'Crispy Buffalo Chicken Salad', 'Tomato', true, true, 0.00, 20),
    ('Specials', 'Specials', 'Crispy Buffalo Chicken Salad', 'Blue Cheese', true, true, 0.00, 30),
    ('Specials', 'Specials', 'Crispy Buffalo Chicken Salad', 'Romaine Lettuce', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Grilled Chicken Italian Sub', 'Grilled Chicken', true, true, 0.00, 10),
    ('Specials', 'Specials', 'Grilled Chicken Italian Sub', 'Roasted Peppers', true, true, 0.00, 20),
    ('Specials', 'Specials', 'Grilled Chicken Italian Sub', 'Fresh Mozzarella', true, true, 0.00, 30),
    ('Specials', 'Specials', 'Grilled Chicken Italian Sub', 'Sun-Dried Tomatoes', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Grilled Chicken Italian Sub', 'Pesto Sauce', true, true, 0.00, 50),
    ('Specials', 'Specials', 'Three Bean Chicken Salad', 'Red Beans', true, true, 0.00, 10),
    ('Specials', 'Specials', 'Three Bean Chicken Salad', 'White Beans', true, true, 0.00, 20),
    ('Specials', 'Specials', 'Three Bean Chicken Salad', 'Black Beans', true, true, 0.00, 30),
    ('Specials', 'Specials', 'Three Bean Chicken Salad', 'Grilled Chicken', true, true, 0.00, 40),
    ('Specials', 'Specials', 'Three Bean Chicken Salad', 'Scallions', true, true, 0.00, 50),
    ('Specials', 'Specials', 'Three Bean Chicken Salad', 'Romaine Lettuce', true, true, 0.00, 70),
    ('Specials', 'Specials', 'Three Bean Chicken Salad', 'Cilantro Lime Vinaigrette', true, true, 0.00, 80),
    ('Specials', 'Specials', 'Three Bean Chicken Salad', 'Cherry Tomatoes', true, true, 0.00, 90),
    ('Lunch & Dinner', 'Appetizers & Fruits', 'Nachos', 'Cheddar', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Appetizers & Fruits', 'Nachos', 'Salsa', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Appetizers & Fruits', 'Nachos', 'Guacamole', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Appetizers & Fruits', 'Nachos', 'Tortilla Chips', true, true, 0.00, 40),
    ('Lunch & Dinner', 'Appetizers & Fruits', 'Nachos', 'Chili', true, true, 0.00, 50),
    ('Lunch & Dinner', 'Appetizers & Fruits', 'Nachos', 'Pico de Gallo', true, true, 0.00, 60),
    ('Lunch & Dinner', 'Soups', 'Crock of Onion Soup', 'Cheese', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Soups', 'Crock of Onion Soup', 'Garlic Bread', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Entrees', 'Szechuan Chicken', 'Vegetables', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Entrees', 'Szechuan Chicken', 'Cashews', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Entrees', 'Chicken Familia', 'Mushrooms', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Entrees', 'Chicken Familia', 'Onion', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Entrees', 'Chicken Familia', 'Potatoes', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Entrees', 'Chicken Familia', 'Garlic', true, true, 0.00, 40),
    ('Lunch & Dinner', 'Entrees', 'Spanish Chicken', 'Onion', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Entrees', 'Spanish Chicken', 'Tomato', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Entrees', 'Spanish Chicken', 'Potatoes', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Entrees', 'Golden Roasted Half Chicken', 'Stuffing', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Entrees', 'Sauteed Calves Liver', 'Onion', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Entrees', 'Roast Turkey with All the Fixins', 'Cranberry Sauce', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Entrees', 'Roast Turkey with All the Fixins', 'Stuffing', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Entrees', 'Southern Fried Chicken', 'Fried Chicken', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Entrees', 'Chicken Lo Mein', 'Fresh Vegetables', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Entrees', 'Chicken Giambotta', 'Sausage', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Entrees', 'Chicken Giambotta', 'Mushrooms', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Entrees', 'Chicken Giambotta', 'Onion', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Entrees', 'Chicken Giambotta', 'Potatoes', true, true, 0.00, 40),
    ('Lunch & Dinner', 'From the Sea', 'Fried Flounder', 'Lemon Wedge', true, true, 0.00, 10),
    ('Lunch & Dinner', 'From the Sea', 'Broiled or Fried Combo Platter', 'Swordfish', true, true, 0.00, 10),
    ('Lunch & Dinner', 'From the Sea', 'Broiled or Fried Combo Platter', 'Flounder', true, true, 0.00, 20),
    ('Lunch & Dinner', 'From the Sea', 'Broiled or Fried Combo Platter', 'Scallops', true, true, 0.00, 30),
    ('Lunch & Dinner', 'From the Sea', 'Broiled or Fried Combo Platter', 'Clams', true, true, 0.00, 40),
    ('Lunch & Dinner', 'From the Sea', 'Broiled or Fried Combo Platter', 'Shrimp', true, true, 0.00, 50),
    ('Lunch & Dinner', 'From the Sea', 'Grilled Shrimp', 'Fresh Vegetables', true, true, 0.00, 10),
    ('Lunch & Dinner', 'From the Sea', 'Grilled Shrimp', 'Garlic Mashed Potatoes', true, true, 0.00, 20),
    ('Lunch & Dinner', 'From the Sea', 'Grilled Shrimp Pasta', 'Onion', true, true, 0.00, 10),
    ('Lunch & Dinner', 'From the Sea', 'Grilled Shrimp Pasta', 'Arugula', true, true, 0.00, 20),
    ('Lunch & Dinner', 'From the Sea', 'Grilled Shrimp Pasta', 'Tomato', true, true, 0.00, 30),
    ('Lunch & Dinner', 'From the Sea', 'Grilled Shrimp Pasta', 'Balsamic', true, true, 0.00, 40),
    ('Lunch & Dinner', 'From the Sea', 'Grilled Shrimp Pasta', 'Pasta', true, true, 0.00, 50),
    ('Lunch & Dinner', 'Prime Steaks & Chops', 'Ground Sirloin', 'Mushrooms', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Prime Steaks & Chops', 'Ground Sirloin', 'Onion', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Prime Steaks & Chops', 'Grilled Center Cut Pork Chops', 'Applesauce', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Prime Steaks & Chops', 'Grilled Center Cut Pork Chops', 'Potato Pancake', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Prime Steaks & Chops', 'Char-Grilled Turkey Steak', 'Turkey', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Prime Steaks & Chops', 'Char-Grilled Turkey Steak', 'Onion', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Prime Steaks & Chops', 'Sliced Skirt Steak Platter', 'Mushrooms', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Prime Steaks & Chops', 'Sliced Skirt Steak Platter', 'Brown Onions', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Prime Steaks & Chops', 'Sliced Skirt Steak Platter', 'Toast', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Italian Specialties', 'Chicken Parmigiana', 'Spaghetti', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Italian Specialties', 'Veal Cutlet Parmigiana', 'Spaghetti', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Italian Specialties', 'Eggplant Parmigiana', 'Spaghetti', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Italian Specialties', 'Linguini', 'Clams', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Italian Specialties', 'Breaded Veal Cutlet', 'Spaghetti', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Italian Specialties', 'Rigatoni & Chicken', 'Spinach', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Italian Specialties', 'Rigatoni & Chicken', 'Sun-Dried Tomatoes', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Italian Specialties', 'Rigatoni & Chicken', 'Garlic White Wine Sauce', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Italian Specialties', 'Linguini Ala Ritz (Spicy or Mild)', 'Clams', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Italian Specialties', 'Linguini Ala Ritz (Spicy or Mild)', 'Shrimp', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Italian Specialties', 'Linguini Ala Ritz (Spicy or Mild)', 'Pasta', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Jewish Specialties', 'Potato Pancakes', 'Sour Cream', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Jewish Specialties', 'Potato Pancakes', 'Applesauce', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Jewish Specialties', 'Kasha Varnishkas', 'Gravy', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Jewish Specialties', 'Chicken in The Pot', 'Chicken', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Jewish Specialties', 'Chicken in The Pot', 'Carrots', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Jewish Specialties', 'Chicken in The Pot', 'Noodles', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Jewish Specialties', 'Chicken in The Pot', 'Matzoh Balls', true, true, 0.00, 40),
    ('Lunch & Dinner', 'Jewish Specialties', 'Flanken in The Pot', 'Carrots', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Jewish Specialties', 'Flanken in The Pot', 'Noodles', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Jewish Specialties', 'Flanken in The Pot', 'Matzoh Balls', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Jewish Specialties', 'Potato Pierogies', 'Brown Onions', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Jewish Specialties', 'Sauteed Chicken Liver', 'Mushrooms', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Jewish Specialties', 'Sauteed Chicken Liver', 'Onion', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Jewish Specialties', 'Sauteed Chicken Liver', 'Rice', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Chunky Shrimp Salad', 'Egg', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Chunky Shrimp Salad', 'Lettuce', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Chunky Shrimp Salad', 'Fresh Vegetables', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Chicken Salad Platter', 'Egg', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Chicken Salad Platter', 'Lettuce', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Chicken Salad Platter', 'Fresh Vegetables', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Tuna Fish Salad Platter', 'Egg', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Tuna Fish Salad Platter', 'Lettuce', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Tuna Fish Salad Platter', 'Fresh Vegetables', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Egg Salad Platter', 'Egg', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Egg Salad Platter', 'Lettuce', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Egg Salad Platter', 'Fresh Vegetables', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Chopped Chicken Liver', 'Egg', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Chopped Chicken Liver', 'Bermuda Onion', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Greek Salad — Small', 'Dressing', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Greek Salad — Large', 'Dressing', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Spinach Salad', 'Bacon', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Spinach Salad', 'Egg', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Spinach Salad', 'Fresh Mushrooms', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Spinach Salad', 'Tomato', true, true, 0.00, 40),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Chef''s Salad', 'Roast Turkey', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Chef''s Salad', 'Roast Beef', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Chef''s Salad', 'Ham', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Chef''s Salad', 'Egg', true, true, 0.00, 40),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Chef''s Salad', 'Mixed Greens', true, true, 0.00, 50),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Chef''s Salad', 'Tomato', true, true, 0.00, 60),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Chef''s Salad', 'Swiss Cheese', true, true, 0.00, 70),
    ('Lunch & Dinner', 'Cold Platters & Salads', 'Sardine Platter', 'Fresh Vegetables', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Cheese Steak Deluxe', 'Fried Onions', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Cheese Steak Deluxe', 'French Fries', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Cheese Steak Deluxe', 'Torpedo Roll', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Grilled Chicken Pasta — Lunch', 'Onion', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Grilled Chicken Pasta — Lunch', 'Arugula', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Grilled Chicken Pasta — Lunch', 'Tomato', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Grilled Chicken Pasta — Lunch', 'Balsamic', true, true, 0.00, 40),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Grilled Chicken Pasta — Lunch', 'Pasta', true, true, 0.00, 50),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Grilled Chicken Pasta — Dinner', 'Onion', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Grilled Chicken Pasta — Dinner', 'Arugula', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Grilled Chicken Pasta — Dinner', 'Tomato', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Grilled Chicken Pasta — Dinner', 'Balsamic', true, true, 0.00, 40),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Grilled Chicken Pasta — Dinner', 'Pasta', true, true, 0.00, 50),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Char-Grilled Chicken Breast Sandwich', 'Lettuce', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Char-Grilled Chicken Breast Sandwich', 'Tomato', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Char-Grilled Chicken Breast Sandwich', 'French Fries', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Sesame Chicken — Lunch', 'Fresh Mushrooms', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Sesame Chicken — Lunch', 'Spinach', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Sesame Chicken — Lunch', 'Tomato', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Sesame Chicken — Dinner', 'Fresh Mushrooms', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Sesame Chicken — Dinner', 'Spinach', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Sesame Chicken — Dinner', 'Tomato', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Chicken Finger Platter', 'Honey Mustard', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Chicken Finger Platter', 'French Fries', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Distinctive Specialties', 'French Dip', 'French Fries', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'French Dip', 'Garlic Bread', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Golden Fried Filet Deluxe', 'French Fries', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Golden Fried Filet Deluxe', 'Bun', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Golden Fried Filet Deluxe', 'Cole Slaw', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Chicken Cheesesteak', 'Fried Onions', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Chicken Cheesesteak', 'French Fries', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Chicken Cheesesteak', 'Torpedo Roll', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Turkey or Chicken Meatloaf Sandwich', 'Gravy', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Turkey or Chicken Meatloaf Sandwich', 'French Fries', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Turkey or Chicken Meatloaf Sandwich', 'Hard Roll', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Veal Patti Parmigiana', 'Torpedo Roll', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Tuna Melt', 'Tomato', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Tuna Melt', 'Cheese', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Chicken Parmigiana Hero', 'Cheese', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Chicken Parmigiana Hero', 'Torpedo Roll', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Cuban Sandwich', 'French Fries', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Gyro', 'Onion', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Gyro', 'Lettuce', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Gyro', 'Tomato', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Gyro', 'Tzatziki Sauce', true, true, 0.00, 40),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Gyro', 'French Fries', true, true, 0.00, 50),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Gyro', 'Pita', true, true, 0.00, 60),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Chicken Wrap', 'Grilled Chicken', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Chicken Wrap', 'Lettuce', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Chicken Wrap', 'Tomato', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Chicken Wrap', 'French Fries', true, true, 0.00, 60),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Chicken Wrap', 'Balsamic Dressing', true, true, 0.00, 70),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Chicken Quesadilla', 'Sour Cream', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Chicken Quesadilla', 'Salsa', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Chili Fiesta', 'Onion', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Chili Fiesta', 'Sour Cream', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Trim Line Features', 'Hot Pasta Primavera', 'Fresh Vegetables', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Trim Line Features', 'Hot Pasta Primavera', 'Cottage Cheese', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Trim Line Features', 'Hot Pasta Primavera', 'Garlic', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Trim Line Features', 'Turkey Bowl', 'Roast Turkey', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Trim Line Features', 'Turkey Bowl', 'Egg', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Trim Line Features', 'Turkey Bowl', 'Dressing', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Trim Line Features', 'Lean Beef or Turkey Patti', 'Cottage Cheese', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Trim Line Features', 'Lean Beef or Turkey Patti', 'Pineapple', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Trim Line Features', 'Diet Riot', 'Tossed Salad', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Trim Line Features', 'Diet Delight', 'Tossed Salad', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Trim Line Features', 'Pineapple Boat', 'Cottage Cheese', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Trim Line Features', 'Fresh Fruit Bowl', 'Lettuce', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Trim Line Features', 'Fresh Fruit Bowl', 'Cottage Cheese', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Trim Line Features', 'Fresh Fruit Bowl', 'Jello', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Trim Line Features', 'Cobb Salad — Lunch', 'Grilled Chicken', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Trim Line Features', 'Cobb Salad — Lunch', 'Bacon', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Trim Line Features', 'Cobb Salad — Lunch', 'Egg', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Trim Line Features', 'Cobb Salad — Lunch', 'Tomato', true, true, 0.00, 40),
    ('Lunch & Dinner', 'Trim Line Features', 'Cobb Salad — Lunch', 'Avocado', true, true, 0.00, 50),
    ('Lunch & Dinner', 'Trim Line Features', 'Cobb Salad — Lunch', 'Blue Cheese', true, true, 0.00, 60),
    ('Lunch & Dinner', 'Trim Line Features', 'Cobb Salad — Lunch', 'Tortilla Shell', true, true, 0.00, 70),
    ('Lunch & Dinner', 'Trim Line Features', 'Cobb Salad — Dinner', 'Grilled Chicken', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Trim Line Features', 'Cobb Salad — Dinner', 'Bacon', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Trim Line Features', 'Cobb Salad — Dinner', 'Egg', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Trim Line Features', 'Cobb Salad — Dinner', 'Tomato', true, true, 0.00, 40),
    ('Lunch & Dinner', 'Trim Line Features', 'Cobb Salad — Dinner', 'Avocado', true, true, 0.00, 50),
    ('Lunch & Dinner', 'Trim Line Features', 'Cobb Salad — Dinner', 'Blue Cheese', true, true, 0.00, 60),
    ('Lunch & Dinner', 'Trim Line Features', 'Cobb Salad — Dinner', 'Tortilla Shell', true, true, 0.00, 70),
    ('Lunch & Dinner', 'Trim Line Features', 'Caesar Italia', 'Grilled Chicken', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Trim Line Features', 'Caesar Italia', 'Onion', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Trim Line Features', 'Caesar Italia', 'Romaine Lettuce', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Trim Line Features', 'Caesar Italia', 'Tomato', true, true, 0.00, 40),
    ('Lunch & Dinner', 'Trim Line Features', 'Caesar Italia', 'Mozzarella', true, true, 0.00, 50),
    ('Lunch & Dinner', 'Trim Line Features', 'Marion’s Chopped Salad — Lunch', 'Sesame Chicken', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Trim Line Features', 'Marion’s Chopped Salad — Lunch', 'Portabella Mushrooms', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Trim Line Features', 'Marion’s Chopped Salad — Lunch', 'Iceberg Lettuce', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Trim Line Features', 'Marion’s Chopped Salad — Lunch', 'Cucumber', true, true, 0.00, 40),
    ('Lunch & Dinner', 'Trim Line Features', 'Marion’s Chopped Salad — Lunch', 'Carrots', true, true, 0.00, 50),
    ('Lunch & Dinner', 'Trim Line Features', 'Marion’s Chopped Salad — Lunch', 'Fresh Mozzarella', true, true, 0.00, 60),
    ('Lunch & Dinner', 'Trim Line Features', 'Marion’s Chopped Salad — Lunch', 'Black Olive Dressing', true, true, 0.00, 70),
    ('Lunch & Dinner', 'Trim Line Features', 'Marion’s Chopped Salad — Lunch', 'Almonds', true, true, 0.00, 80),
    ('Lunch & Dinner', 'Trim Line Features', 'Marion’s Chopped Salad — Dinner', 'Sesame Chicken', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Trim Line Features', 'Marion’s Chopped Salad — Dinner', 'Portabella Mushrooms', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Trim Line Features', 'Marion’s Chopped Salad — Dinner', 'Iceberg Lettuce', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Trim Line Features', 'Marion’s Chopped Salad — Dinner', 'Cucumber', true, true, 0.00, 40),
    ('Lunch & Dinner', 'Trim Line Features', 'Marion’s Chopped Salad — Dinner', 'Carrots', true, true, 0.00, 50),
    ('Lunch & Dinner', 'Trim Line Features', 'Marion’s Chopped Salad — Dinner', 'Fresh Mozzarella', true, true, 0.00, 60),
    ('Lunch & Dinner', 'Trim Line Features', 'Marion’s Chopped Salad — Dinner', 'Black Olive Dressing', true, true, 0.00, 70),
    ('Lunch & Dinner', 'Trim Line Features', 'Marion’s Chopped Salad — Dinner', 'Almonds', true, true, 0.00, 80),
    ('Lunch & Dinner', 'Trim Line Features', 'Ritz Salad with Grilled Chicken — Lunch', 'Red Onion', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Trim Line Features', 'Ritz Salad with Grilled Chicken — Lunch', 'Iceberg Lettuce', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Trim Line Features', 'Ritz Salad with Grilled Chicken — Lunch', 'Cucumber', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Trim Line Features', 'Ritz Salad with Grilled Chicken — Lunch', 'Carrots', true, true, 0.00, 40),
    ('Lunch & Dinner', 'Trim Line Features', 'Ritz Salad with Grilled Chicken — Lunch', 'Chickpeas', true, true, 0.00, 50),
    ('Lunch & Dinner', 'Trim Line Features', 'Ritz Salad with Grilled Chicken — Lunch', 'Olives', true, true, 0.00, 60),
    ('Lunch & Dinner', 'Trim Line Features', 'Ritz Salad with Grilled Chicken — Lunch', 'Fresh Mozzarella', true, true, 0.00, 70),
    ('Lunch & Dinner', 'Trim Line Features', 'Ritz Salad with Grilled Chicken — Lunch', 'Balsamic Vinaigrette', true, true, 0.00, 80),
    ('Lunch & Dinner', 'Trim Line Features', 'Ritz Salad with Grilled Chicken — Dinner', 'Red Onion', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Trim Line Features', 'Ritz Salad with Grilled Chicken — Dinner', 'Iceberg Lettuce', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Trim Line Features', 'Ritz Salad with Grilled Chicken — Dinner', 'Cucumber', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Trim Line Features', 'Ritz Salad with Grilled Chicken — Dinner', 'Carrots', true, true, 0.00, 40),
    ('Lunch & Dinner', 'Trim Line Features', 'Ritz Salad with Grilled Chicken — Dinner', 'Chickpeas', true, true, 0.00, 50),
    ('Lunch & Dinner', 'Trim Line Features', 'Ritz Salad with Grilled Chicken — Dinner', 'Olives', true, true, 0.00, 60),
    ('Lunch & Dinner', 'Trim Line Features', 'Ritz Salad with Grilled Chicken — Dinner', 'Fresh Mozzarella', true, true, 0.00, 70),
    ('Lunch & Dinner', 'Trim Line Features', 'Ritz Salad with Grilled Chicken — Dinner', 'Balsamic Vinaigrette', true, true, 0.00, 80),
    ('Lunch & Dinner', 'Trim Line Features', 'Blackened Salmon Salad', 'Blackened Salmon', true, true, 0.00, 10),
    ('Lunch & Dinner', 'Trim Line Features', 'Blackened Salmon Salad', 'Romaine Lettuce', true, true, 0.00, 20),
    ('Lunch & Dinner', 'Trim Line Features', 'Blackened Salmon Salad', 'Tomato', true, true, 0.00, 30),
    ('Lunch & Dinner', 'Trim Line Features', 'Blackened Salmon Salad', 'Provolone', true, true, 0.00, 40),
    ('Lunch & Dinner', 'Trim Line Features', 'Blackened Salmon Salad', 'Lemon Vinaigrette', true, true, 0.00, 50),
    ('Lunch & Dinner', 'Trim Line Features', 'Blackened Salmon Salad', 'Walnuts', true, true, 0.00, 60),
    ('Lunch & Dinner', 'From the Char-Broiler', 'Steak Sandwich', 'Skirt Steak', true, true, 0.00, 10),
    ('Lunch & Dinner', 'From the Char-Broiler', 'Steak Sandwich', 'Sautéed Onions', true, true, 0.00, 30),
    ('Lunch & Dinner', 'From the Char-Broiler', 'Steak Sandwich', 'French Fries', true, true, 0.00, 40),
    ('Lunch & Dinner', 'From the Char-Broiler', 'Steak Sandwich', 'Garlic Bread', true, true, 0.00, 50),
    ('Sandwiches & Deli', 'Deli', 'Corned Beef Reuben', 'Sauerkraut', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Deli', 'Corned Beef Reuben', 'Swiss Cheese', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Deli', 'Corned Beef Reuben', 'Russian Dressing', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Deli', 'Pastrami Reuben', 'Sauerkraut', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Deli', 'Pastrami Reuben', 'Swiss Cheese', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Deli', 'Pastrami Reuben', 'Russian Dressing', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Deli', 'Turkey Reuben', 'Swiss Cheese', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Deli', 'Turkey Reuben', 'Russian Dressing', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Deli', 'Turkey Reuben', 'Cole Slaw', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Deli', 'Corned Beef & Pastrami', 'Russian Dressing', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Deli', 'Corned Beef & Pastrami', 'Cole Slaw', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Deli', 'Corned Beef & Chopped Liver', 'Russian Dressing', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Deli', 'Corned Beef & Chopped Liver', 'Cole Slaw', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Deli', 'Turkey, Chopped Liver & Onion', 'Russian Dressing', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Deli', 'Turkey, Chopped Liver & Onion', 'Cole Slaw', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Deli', 'Turkey & Swiss Cheese', 'Russian Dressing', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Deli', 'Turkey & Swiss Cheese', 'Cole Slaw', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Deli', 'Hot Pastrami or Corned Beef', 'Potato Pancake', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Deli', 'Hot Pastrami or Corned Beef', 'Horseradish', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Deli', 'Braised Brisket of Beef', 'Applesauce', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Deli', 'Braised Brisket of Beef', 'Potato Pancake', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Sandwiches', 'Bacon, Lettuce & Tomato', 'Bacon', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Sandwiches', 'Bacon, Lettuce & Tomato', 'Lettuce', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Sandwiches', 'Bacon, Lettuce & Tomato', 'Tomato', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Sandwiches', 'Lettuce & Tomato Sandwich', 'Lettuce', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Sandwiches', 'Lettuce & Tomato Sandwich', 'Tomato', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Hot Open Sandwiches', 'Open-Faced Hot Turkey Sandwich', 'Gravy', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Hot Open Sandwiches', 'Open-Faced Hot Turkey Sandwich', 'French Fries', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Hot Open Sandwiches', 'Open-Faced Hot Roast Beef Sandwich', 'Gravy', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Hot Open Sandwiches', 'Open-Faced Hot Roast Beef Sandwich', 'French Fries', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Hot Open Sandwiches', 'Open-Faced Brisket of Beef', 'Gravy', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Hot Open Sandwiches', 'Open-Faced Brisket of Beef', 'French Fries', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Club: Sliced Turkey, Bacon, Lettuce & Tomato', 'Roast Turkey', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Club: Sliced Turkey, Bacon, Lettuce & Tomato', 'Bacon', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Club: Sliced Turkey, Bacon, Lettuce & Tomato', 'Lettuce', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Club: Sliced Turkey, Bacon, Lettuce & Tomato', 'Tomato', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Tuna Fish Salad, Sliced Egg, Lettuce & Tomato', 'Tuna', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Tuna Fish Salad, Sliced Egg, Lettuce & Tomato', 'Egg', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Tuna Fish Salad, Sliced Egg, Lettuce & Tomato', 'Lettuce', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Tuna Fish Salad, Sliced Egg, Lettuce & Tomato', 'Tomato', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Chicken Salad, Bacon, Lettuce & Tomato', 'Chicken', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Chicken Salad, Bacon, Lettuce & Tomato', 'Bacon', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Chicken Salad, Bacon, Lettuce & Tomato', 'Lettuce', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Chicken Salad, Bacon, Lettuce & Tomato', 'Tomato', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Egg Salad, Bacon, Lettuce & Tomato', 'Egg', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Egg Salad, Bacon, Lettuce & Tomato', 'Bacon', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Egg Salad, Bacon, Lettuce & Tomato', 'Lettuce', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Egg Salad, Bacon, Lettuce & Tomato', 'Tomato', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Roast Beef, Imported Swiss Cheese, Lettuce & Tomato', 'Roast Beef', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Roast Beef, Imported Swiss Cheese, Lettuce & Tomato', 'Swiss Cheese', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Roast Beef, Imported Swiss Cheese, Lettuce & Tomato', 'Lettuce', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Roast Beef, Imported Swiss Cheese, Lettuce & Tomato', 'Tomato', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Ham, Imported Swiss Cheese, Lettuce & Tomato', 'Ham', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Ham, Imported Swiss Cheese, Lettuce & Tomato', 'Swiss Cheese', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Ham, Imported Swiss Cheese, Lettuce & Tomato', 'Lettuce', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Ham, Imported Swiss Cheese, Lettuce & Tomato', 'Tomato', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Chopped Chicken Liver, Bacon, Lettuce & Tomato', 'Chopped Liver', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Chopped Chicken Liver, Bacon, Lettuce & Tomato', 'Bacon', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Chopped Chicken Liver, Bacon, Lettuce & Tomato', 'Lettuce', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Chopped Chicken Liver, Bacon, Lettuce & Tomato', 'Tomato', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Chunky Shrimp Salad, Bacon, Lettuce, Tomato & Mayonnaise', 'Shrimp', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Chunky Shrimp Salad, Bacon, Lettuce, Tomato & Mayonnaise', 'Bacon', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Chunky Shrimp Salad, Bacon, Lettuce, Tomato & Mayonnaise', 'Lettuce', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Chunky Shrimp Salad, Bacon, Lettuce, Tomato & Mayonnaise', 'Tomato', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Chunky Shrimp Salad, Bacon, Lettuce, Tomato & Mayonnaise', 'Mayo', true, true, 0.00, 50),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Grilled Chicken Club with Bacon, Lettuce & Tomato', 'Grilled Chicken', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Grilled Chicken Club with Bacon, Lettuce & Tomato', 'Bacon', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Grilled Chicken Club with Bacon, Lettuce & Tomato', 'Lettuce', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Grilled Chicken Club with Bacon, Lettuce & Tomato', 'Tomato', true, true, 0.00, 40),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Hamburger Club with Bacon, Lettuce & Tomato', 'Burger Patty', true, true, 0.00, 10),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Hamburger Club with Bacon, Lettuce & Tomato', 'Bacon', true, true, 0.00, 20),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Hamburger Club with Bacon, Lettuce & Tomato', 'Lettuce', true, true, 0.00, 30),
    ('Sandwiches & Deli', 'Triple Decker Sandwiches', 'Hamburger Club with Bacon, Lettuce & Tomato', 'Tomato', true, true, 0.00, 40),
    ('Sides & Sweets', 'Side Orders', 'Hard Roll with Butter', 'Butter', true, true, 0.00, 10),
    ('Sides & Sweets', 'Side Orders', 'Toast with Butter & Jelly', 'Butter', true, true, 0.00, 10),
    ('Sides & Sweets', 'Side Orders', 'Toast with Butter & Jelly', 'Jelly', true, true, 0.00, 20),
    ('Sides & Sweets', 'Side Orders', 'English Muffin with Butter & Jelly', 'Butter', true, true, 0.00, 10),
    ('Sides & Sweets', 'Side Orders', 'English Muffin with Butter & Jelly', 'Jelly', true, true, 0.00, 20),
    ('Breakfast', 'Eggs', 'Eggs Benedict', 'Home Fries', true, true, 0.00, 10),
    ('Breakfast', 'Eggs', 'Homemade Blintzes', 'Cheese', true, true, 0.00, 10),
    ('Breakfast', 'Eggs', 'Homemade Blintzes', 'Sour Cream', true, true, 0.00, 20),
    ('Breakfast', 'Eggs', 'Homemade Blintzes', 'Blueberries', true, true, 0.00, 30),
    ('Breakfast', 'Egg Sandwiches', 'Egg & Cheese', 'Egg', true, true, 0.00, 10),
    ('Breakfast', 'Egg Sandwiches', 'Egg & Cheese', 'Cheese', true, true, 0.00, 20),
    ('Breakfast', 'Egg Sandwiches', 'Taylor Ham Sandwich', 'Taylor Ham', true, true, 0.00, 10),
    ('Breakfast', 'Egg Sandwiches', 'Taylor Ham & Cheese', 'Taylor Ham', true, true, 0.00, 10),
    ('Breakfast', 'Egg Sandwiches', 'Taylor Ham & Cheese', 'Cheese', true, true, 0.00, 20),
    ('Breakfast', 'Egg Sandwiches', 'Taylor Ham & Egg', 'Taylor Ham', true, true, 0.00, 10),
    ('Breakfast', 'Egg Sandwiches', 'Taylor Ham & Egg', 'Egg', true, true, 0.00, 20),
    ('Breakfast', 'Egg Sandwiches', 'Taylor Ham, Egg & Cheese', 'Taylor Ham', true, true, 0.00, 10),
    ('Breakfast', 'Egg Sandwiches', 'Taylor Ham, Egg & Cheese', 'Egg', true, true, 0.00, 20),
    ('Breakfast', 'Egg Sandwiches', 'Taylor Ham, Egg & Cheese', 'Cheese', true, true, 0.00, 30),
    ('Breakfast', 'Egg Sandwiches', 'Avocado Toast Platter', 'Egg', true, true, 0.00, 10),
    ('Breakfast', 'Egg Sandwiches', 'Avocado Toast Platter', 'Avocado', true, true, 0.00, 20),
    ('Breakfast', 'Egg Sandwiches', 'Avocado Toast Platter', 'Toast', true, true, 0.00, 30),
    ('Breakfast', 'Egg Sandwiches', 'Μatzon Brei', 'Sour Cream', true, true, 0.00, 10),
    ('Breakfast', 'Egg Sandwiches', 'Μatzon Brei', 'Applesauce', true, true, 0.00, 20),
    ('Breakfast', 'Omelettes', 'American Cheese', 'American Cheese', true, true, 0.00, 10),
    ('Breakfast', 'Omelettes', 'Imported Swiss Cheese', 'Swiss Cheese', true, true, 0.00, 10),
    ('Breakfast', 'Omelettes', 'Cheddar Cheese', 'Cheddar', true, true, 0.00, 10),
    ('Breakfast', 'Omelettes', 'Ham & Cheese', 'Ham', true, true, 0.00, 10),
    ('Breakfast', 'Omelettes', 'Ham & Cheese', 'Cheese', true, true, 0.00, 20),
    ('Breakfast', 'Omelettes', 'Turkey', 'Turkey', true, true, 0.00, 10),
    ('Breakfast', 'Omelettes', 'Feta & Tomato', 'Feta', true, true, 0.00, 10),
    ('Breakfast', 'Omelettes', 'Feta & Tomato', 'Tomato', true, true, 0.00, 20),
    ('Breakfast', 'Omelettes', 'Salami & Eggs (Pancake Style)', 'Salami', true, true, 0.00, 10),
    ('Breakfast', 'Omelettes', 'Salami & Eggs (Pancake Style)', 'Egg', true, true, 0.00, 20),
    ('Breakfast', 'Omelettes', 'Sausage', 'Sausage', true, true, 0.00, 10),
    ('Breakfast', 'Omelettes', 'Onion', 'Onion', true, true, 0.00, 10),
    ('Breakfast', 'Omelettes', 'Fresh Mushrooms', 'Fresh Mushrooms', true, true, 0.00, 10),
    ('Breakfast', 'Omelettes', 'Chicken Liver', 'Fresh Mushrooms', true, true, 0.00, 10),
    ('Breakfast', 'Omelettes', 'Chicken Liver', 'Onion', true, true, 0.00, 20),
    ('Breakfast', 'Omelettes', 'Chicken Liver', 'Chicken Liver', true, true, 0.00, 30),
    ('Breakfast', 'Omelettes', 'Nova & Onion', 'Nova', true, true, 0.00, 10),
    ('Breakfast', 'Omelettes', 'Nova & Onion', 'Onion', true, true, 0.00, 20),
    ('Breakfast', 'Omelettes', 'Spinach', 'Spinach', true, true, 0.00, 10),
    ('Breakfast', 'Omelettes', 'Broccoli', 'Broccoli', true, true, 0.00, 10),
    ('Breakfast', 'Omelettes', 'Scallion & Cream Cheese', 'Scallions', true, true, 0.00, 10),
    ('Breakfast', 'Omelettes', 'Scallion & Cream Cheese', 'Cream Cheese', true, true, 0.00, 20),
    ('Breakfast', 'Omelettes', 'Farmer''s Omelette', 'Mushrooms', true, true, 0.00, 10),
    ('Breakfast', 'Omelettes', 'Farmer''s Omelette', 'Green Peppers', true, true, 0.00, 20),
    ('Breakfast', 'Omelettes', 'Farmer''s Omelette', 'Onion', true, true, 0.00, 30),
    ('Breakfast', 'Omelettes', 'Farmer''s Omelette', 'Tomato', true, true, 0.00, 40),
    ('Breakfast', 'Omelettes', 'Farmer''s Omelette', 'Broccoli', true, true, 0.00, 50),
    ('Breakfast', 'Omelettes', 'Italian Omelette', 'Sausage', true, true, 0.00, 10),
    ('Breakfast', 'Omelettes', 'Italian Omelette', 'Mushrooms', true, true, 0.00, 20),
    ('Breakfast', 'Omelettes', 'Italian Omelette', 'Peppers', true, true, 0.00, 30),
    ('Breakfast', 'Omelettes', 'Italian Omelette', 'Mozzarella', true, true, 0.00, 40),
    ('Breakfast', 'From the Griddle', 'German Apple Pancake', 'Apple', true, true, 0.00, 10),
    ('Breakfast', 'From the Griddle', 'German Apple Pancake', 'Cinnamon Sugar', true, true, 0.00, 20),
    ('Breakfast', 'Bagel Bin', 'Toasted Bagel with Butter & Jelly', 'Butter', true, true, 0.00, 10),
    ('Breakfast', 'Bagel Bin', 'Toasted Bagel with Butter & Jelly', 'Jelly', true, true, 0.00, 20),
    ('Breakfast', 'Bagel Bin', 'Toasted Bagel with Cream Cheese', 'Cream Cheese', true, true, 0.00, 10),
    ('Breakfast', 'Bagel Bin', 'Nova Platter', 'Bermuda Onion', true, true, 0.00, 10),
    ('Breakfast', 'Bagel Bin', 'Nova Platter', 'Lettuce', true, true, 0.00, 20),
    ('Breakfast', 'Bagel Bin', 'Nova Platter', 'Tomato', true, true, 0.00, 30),
    ('Breakfast', 'Bagel Bin', 'Nova Platter', 'Cucumber', true, true, 0.00, 40),
    ('Breakfast', 'Bagel Bin', 'Nova Platter', 'Cream Cheese', true, true, 0.00, 50),
    ('Breakfast', 'Bagel Bin', 'Nova Platter', 'Bagel', true, true, 0.00, 60),
    ('Breakfast', 'Bagel Bin', 'Smoked Whitefish Platter', 'Bermuda Onion', true, true, 0.00, 10),
    ('Breakfast', 'Bagel Bin', 'Smoked Whitefish Platter', 'Lettuce', true, true, 0.00, 20),
    ('Breakfast', 'Bagel Bin', 'Smoked Whitefish Platter', 'Tomato', true, true, 0.00, 30),
    ('Breakfast', 'Bagel Bin', 'Smoked Whitefish Platter', 'Cucumber', true, true, 0.00, 40),
    ('Breakfast', 'Bagel Bin', 'Smoked Whitefish Platter', 'Cream Cheese', true, true, 0.00, 50),
    ('Breakfast', 'Bagel Bin', 'Smoked Whitefish Platter', 'Bagel', true, true, 0.00, 60),
    ('Breakfast', 'Bagel Bin', 'Smoked Whitefish Salad Platter', 'Bermuda Onion', true, true, 0.00, 10),
    ('Breakfast', 'Bagel Bin', 'Smoked Whitefish Salad Platter', 'Lettuce', true, true, 0.00, 20),
    ('Breakfast', 'Bagel Bin', 'Smoked Whitefish Salad Platter', 'Tomato', true, true, 0.00, 30),
    ('Breakfast', 'Bagel Bin', 'Smoked Whitefish Salad Platter', 'Cucumber', true, true, 0.00, 40),
    ('Breakfast', 'Bagel Bin', 'Smoked Whitefish Salad Platter', 'Cream Cheese', true, true, 0.00, 50),
    ('Breakfast', 'Bagel Bin', 'Smoked Whitefish Salad Platter', 'Bagel', true, true, 0.00, 60);

  INSERT INTO menu_item_ingredients (
    menu_item_id,
    ingredient_id,
    can_remove,
    can_extra,
    extra_price,
    sort_order
  )
  SELECT
    item.id,
    ingredient.id,
    seed.can_remove,
    seed.can_extra,
    seed.extra_price,
    seed.sort_order
  FROM seed_menu_components seed
  JOIN menu_groups group_record
    ON group_record.name = seed.group_name
  JOIN menu_categories category
    ON category.group_id = group_record.id
   AND category.name = seed.category_name
  JOIN menu_items item
    ON item.category_id = category.id
   AND item.name = seed.item_name
   AND item.is_modifier = false
  JOIN ingredients ingredient
    ON lower(ingredient.name) = lower(seed.ingredient_name)
  ON CONFLICT (menu_item_id, ingredient_id) DO UPDATE
  SET
    can_remove = EXCLUDED.can_remove,
    can_extra = EXCLUDED.can_extra,
    extra_price = EXCLUDED.extra_price,
    sort_order = EXCLUDED.sort_order,
    updated_at = now();


  CREATE TEMP TABLE seed_menu_choices (
    group_name text NOT NULL,
    category_name text NOT NULL,
    item_name text NOT NULL,
    choice_label text NOT NULL,
    min_selections integer NOT NULL,
    max_selections integer,
    group_sort_order integer NOT NULL,
    option_label text NOT NULL,
    ingredient_name text,
    price_adjustment numeric(10, 2) NOT NULL,
    option_sort_order integer NOT NULL,
    is_default boolean NOT NULL
  ) ON COMMIT DROP;

  INSERT INTO seed_menu_choices (
    group_name,
    category_name,
    item_name,
    choice_label,
    min_selections,
    max_selections,
    group_sort_order,
    option_label,
    ingredient_name,
    price_adjustment,
    option_sort_order,
    is_default
  )
  VALUES
    ('Specials', 'Specials', 'Strawberry Spinach Salad', 'Choose Protein', 1, 1, 50, 'Blackened Salmon', 'Blackened Salmon', 0.00, 10, false),
    ('Specials', 'Specials', 'Strawberry Spinach Salad', 'Choose Protein', 1, 1, 50, 'Chicken', 'Chicken', 0.00, 20, false),
    ('Specials', 'Specials', 'Mango Barley Chicken Salad', 'Choose Chicken', 1, 1, 50, 'Sesame Chicken', 'Sesame Chicken', 0.00, 10, false),
    ('Specials', 'Specials', 'Mango Barley Chicken Salad', 'Choose Chicken', 1, 1, 50, 'Marinated Chicken', 'Marinated Chicken', 0.00, 20, false),
    ('Lunch & Dinner', 'From the Sea', 'Broiled Salmon or Tuna', 'Choose Fish', 1, 1, 50, 'Salmon', 'Salmon', 0.00, 10, false),
    ('Lunch & Dinner', 'From the Sea', 'Broiled Salmon or Tuna', 'Choose Fish', 1, 1, 50, 'Tuna', 'Tuna', 0.00, 20, false),
    ('Lunch & Dinner', 'From the Sea', 'Broiled or Fried Combo Platter', 'Preparation', 1, 1, 50, 'Broiled', NULL, 0.00, 10, false),
    ('Lunch & Dinner', 'From the Sea', 'Broiled or Fried Combo Platter', 'Preparation', 1, 1, 50, 'Fried', NULL, 0.00, 20, false),
    ('Lunch & Dinner', 'Italian Specialties', 'Linguini', 'Choose Sauce', 1, 1, 50, 'White Clam Sauce', NULL, 0.00, 10, false),
    ('Lunch & Dinner', 'Italian Specialties', 'Linguini', 'Choose Sauce', 1, 1, 50, 'Red Clam Sauce', NULL, 0.00, 20, false),
    ('Lunch & Dinner', 'Italian Specialties', 'Linguini Ala Ritz (Spicy or Mild)', 'Choose Heat', 1, 1, 50, 'Mild', NULL, 0.00, 10, false),
    ('Lunch & Dinner', 'Italian Specialties', 'Linguini Ala Ritz (Spicy or Mild)', 'Choose Heat', 1, 1, 50, 'Spicy', NULL, 0.00, 20, false),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Char-Grilled Chicken Breast Sandwich', 'Choose Bread', 1, 1, 50, 'Bun', 'Bun', 0.00, 10, false),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Char-Grilled Chicken Breast Sandwich', 'Choose Bread', 1, 1, 50, 'Focaccia Bread', 'Focaccia Bread', 0.00, 20, false),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Stir-Fried Fresh Vegetables', 'Choose Sauce', 1, 1, 50, 'Soy Sauce', 'Soy Sauce', 0.00, 10, false),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Stir-Fried Fresh Vegetables', 'Choose Sauce', 1, 1, 50, 'Garlic & Olive Oil', 'Garlic & Olive Oil', 0.00, 20, false),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Turkey or Chicken Meatloaf Sandwich', 'Choose Meatloaf', 1, 1, 50, 'Turkey Meatloaf', 'Turkey Meatloaf', 0.00, 10, false),
    ('Lunch & Dinner', 'Distinctive Specialties', 'Turkey or Chicken Meatloaf Sandwich', 'Choose Meatloaf', 1, 1, 50, 'Chicken Meatloaf', 'Chicken Meatloaf', 0.00, 20, false),
    ('Lunch & Dinner', 'Trim Line Features', 'Lean Beef or Turkey Patti', 'Choose Patty', 1, 1, 50, 'Lean Beef', 'Lean Beef Patty', 0.00, 10, false),
    ('Lunch & Dinner', 'Trim Line Features', 'Lean Beef or Turkey Patti', 'Choose Patty', 1, 1, 50, 'Turkey', 'Turkey Patty', 0.00, 20, false),
    ('Lunch & Dinner', 'Trim Line Features', 'Diet Riot', 'Choose Burger', 1, 1, 50, 'Turkey Burger', 'Turkey Burger', 0.00, 10, false),
    ('Lunch & Dinner', 'Trim Line Features', 'Diet Riot', 'Choose Burger', 1, 1, 50, 'Chicken Burger', 'Chicken Burger', 0.00, 20, false),
    ('Sandwiches & Deli', 'Deli', 'Hot Pastrami or Corned Beef', 'Choose Meat', 1, 1, 50, 'Pastrami', 'Pastrami', 0.00, 10, false),
    ('Sandwiches & Deli', 'Deli', 'Hot Pastrami or Corned Beef', 'Choose Meat', 1, 1, 50, 'Corned Beef', 'Corned Beef', 0.00, 20, false),
    ('Sandwiches & Deli', 'Sandwiches', 'Grilled American or Swiss Cheese', 'Choose Cheese', 1, 1, 50, 'American Cheese', 'American Cheese', 0.00, 10, false),
    ('Sandwiches & Deli', 'Sandwiches', 'Grilled American or Swiss Cheese', 'Choose Cheese', 1, 1, 50, 'Swiss Cheese', 'Swiss Cheese', 0.00, 20, false),
    ('Sandwiches & Deli', 'Sandwiches', 'Grilled American or Swiss Cheese', 'Add Meat', 0, 1, 60, 'Bacon', 'Bacon', 2.00, 10, false),
    ('Sandwiches & Deli', 'Sandwiches', 'Grilled American or Swiss Cheese', 'Add Meat', 0, 1, 60, 'Ham', 'Ham', 2.00, 20, false),
    ('Sandwiches & Deli', 'Sandwiches', 'Grilled American or Swiss Cheese', 'Add Meat', 0, 1, 60, 'Taylor Ham', 'Taylor Ham', 2.00, 30, false),
    ('Sandwiches & Deli', 'Sandwiches', 'Grilled American or Swiss Cheese', 'Add Tomato', 0, 1, 70, 'Tomato', 'Tomato', 1.00, 10, false),
    ('Sides & Sweets', 'Side Orders', 'Homemade Potato Salad or Homemade Cole Slaw', 'Choose Side', 1, 1, 50, 'Potato Salad', 'Potato Salad', 0.00, 10, false),
    ('Sides & Sweets', 'Side Orders', 'Homemade Potato Salad or Homemade Cole Slaw', 'Choose Side', 1, 1, 50, 'Cole Slaw', 'Cole Slaw', 0.00, 20, false),
    ('Sides & Sweets', 'Side Orders', 'Sausage (Pork or Turkey)', 'Choose Sausage', 1, 1, 50, 'Pork Sausage', 'Pork Sausage', 0.00, 10, false),
    ('Sides & Sweets', 'Side Orders', 'Sausage (Pork or Turkey)', 'Choose Sausage', 1, 1, 50, 'Turkey Sausage', 'Turkey Sausage', 0.00, 20, false),
    ('Sides & Sweets', 'Side Orders', 'Bacon, Ham, or Taylor Ham', 'Choose Breakfast Meat', 1, 1, 50, 'Bacon', 'Bacon', 0.00, 10, false),
    ('Sides & Sweets', 'Side Orders', 'Bacon, Ham, or Taylor Ham', 'Choose Breakfast Meat', 1, 1, 50, 'Ham', 'Ham', 0.00, 20, false),
    ('Sides & Sweets', 'Side Orders', 'Bacon, Ham, or Taylor Ham', 'Choose Breakfast Meat', 1, 1, 50, 'Taylor Ham', 'Taylor Ham', 0.00, 30, false),
    ('Sides & Sweets', 'Side Orders', 'Blueberry Muffin or Apple Cinnamon Muffin', 'Choose Muffin', 1, 1, 50, 'Blueberry Muffin', NULL, 0.00, 10, false),
    ('Sides & Sweets', 'Side Orders', 'Blueberry Muffin or Apple Cinnamon Muffin', 'Choose Muffin', 1, 1, 50, 'Apple Cinnamon Muffin', NULL, 0.00, 20, false),
    ('Sides & Sweets', 'Side Orders', 'Corn or Bran Muffin', 'Choose Muffin', 1, 1, 50, 'Corn Muffin', NULL, 0.00, 10, false),
    ('Sides & Sweets', 'Side Orders', 'Corn or Bran Muffin', 'Choose Muffin', 1, 1, 50, 'Bran Muffin', NULL, 0.00, 20, false),
    ('Sides & Sweets', 'Homemade Desserts', 'Apple, Cherry or Blueberry Crumb Pie', 'Choose Pie', 1, 1, 50, 'Apple', NULL, 0.00, 10, false),
    ('Sides & Sweets', 'Homemade Desserts', 'Apple, Cherry or Blueberry Crumb Pie', 'Choose Pie', 1, 1, 50, 'Cherry', NULL, 0.00, 20, false),
    ('Sides & Sweets', 'Homemade Desserts', 'Apple, Cherry or Blueberry Crumb Pie', 'Choose Pie', 1, 1, 50, 'Blueberry', NULL, 0.00, 30, false),
    ('Kids', 'Kids Korner', 'Hamburger or Grilled Chicken Sandwich', 'Choose Sandwich', 1, 1, 50, 'Hamburger', 'Burger Patty', 0.00, 10, false),
    ('Kids', 'Kids Korner', 'Hamburger or Grilled Chicken Sandwich', 'Choose Sandwich', 1, 1, 50, 'Grilled Chicken Sandwich', 'Grilled Chicken', 0.00, 20, false),
    ('Kids', 'Kids Korner', 'Grilled Cheese or Peanut Butter & Jelly', 'Choose Sandwich', 1, 1, 50, 'Grilled Cheese', 'Grilled Cheese', 0.00, 10, false),
    ('Kids', 'Kids Korner', 'Grilled Cheese or Peanut Butter & Jelly', 'Choose Sandwich', 1, 1, 50, 'Peanut Butter & Jelly', 'Peanut Butter & Jelly', 0.00, 20, false),
    ('Breakfast', 'Eggs', 'Two Eggs (Any Style)', 'Egg Style', 1, 1, 30, 'Scrambled', NULL, 0.00, 10, false),
    ('Breakfast', 'Eggs', 'Two Eggs (Any Style)', 'Egg Style', 1, 1, 30, 'Sunny Side Up', NULL, 0.00, 20, false),
    ('Breakfast', 'Eggs', 'Two Eggs (Any Style)', 'Egg Style', 1, 1, 30, 'Over Easy', NULL, 0.00, 30, false),
    ('Breakfast', 'Eggs', 'Two Eggs (Any Style)', 'Egg Style', 1, 1, 30, 'Over Medium', NULL, 0.00, 40, false),
    ('Breakfast', 'Eggs', 'Two Eggs (Any Style)', 'Egg Style', 1, 1, 30, 'Over Hard', NULL, 0.00, 50, false),
    ('Breakfast', 'Eggs', 'Single Egg', 'Egg Style', 1, 1, 30, 'Scrambled', NULL, 0.00, 10, false),
    ('Breakfast', 'Eggs', 'Single Egg', 'Egg Style', 1, 1, 30, 'Sunny Side Up', NULL, 0.00, 20, false),
    ('Breakfast', 'Eggs', 'Single Egg', 'Egg Style', 1, 1, 30, 'Over Easy', NULL, 0.00, 30, false),
    ('Breakfast', 'Eggs', 'Single Egg', 'Egg Style', 1, 1, 30, 'Over Medium', NULL, 0.00, 40, false),
    ('Breakfast', 'Eggs', 'Single Egg', 'Egg Style', 1, 1, 30, 'Over Hard', NULL, 0.00, 50, false),
    ('Breakfast', 'Egg Sandwiches', 'Avocado Toast Platter', 'Egg Style', 1, 1, 30, 'Scrambled', NULL, 0.00, 10, false),
    ('Breakfast', 'Egg Sandwiches', 'Avocado Toast Platter', 'Egg Style', 1, 1, 30, 'Sunny Side Up', NULL, 0.00, 20, false),
    ('Breakfast', 'Egg Sandwiches', 'Avocado Toast Platter', 'Egg Style', 1, 1, 30, 'Over Easy', NULL, 0.00, 30, false),
    ('Breakfast', 'Egg Sandwiches', 'Avocado Toast Platter', 'Egg Style', 1, 1, 30, 'Over Medium', NULL, 0.00, 40, false),
    ('Breakfast', 'Egg Sandwiches', 'Avocado Toast Platter', 'Egg Style', 1, 1, 30, 'Over Hard', NULL, 0.00, 50, false),
    ('Breakfast', 'Egg Sandwiches', 'Ham or Bacon or Salami or Sausage & Egg', 'Choose Meat', 1, 1, 50, 'Ham', 'Ham', 0.00, 10, false),
    ('Breakfast', 'Egg Sandwiches', 'Ham or Bacon or Salami or Sausage & Egg', 'Choose Meat', 1, 1, 50, 'Bacon', 'Bacon', 0.00, 20, false),
    ('Breakfast', 'Egg Sandwiches', 'Ham or Bacon or Salami or Sausage & Egg', 'Choose Meat', 1, 1, 50, 'Salami', 'Salami', 0.00, 30, false),
    ('Breakfast', 'Egg Sandwiches', 'Ham or Bacon or Salami or Sausage & Egg', 'Choose Meat', 1, 1, 50, 'Sausage', 'Sausage', 0.00, 40, false),
    ('Breakfast', 'Omelettes', 'Bacon or Ham', 'Choose Meat', 1, 1, 50, 'Bacon', 'Bacon', 0.00, 10, false),
    ('Breakfast', 'Omelettes', 'Bacon or Ham', 'Choose Meat', 1, 1, 50, 'Ham', 'Ham', 0.00, 20, false),
    ('Breakfast', 'Egg Sandwiches', 'Challah French Toast (Plain or Raisin)', 'Choose Challah', 1, 1, 50, 'Plain', NULL, 0.00, 10, false),
    ('Breakfast', 'Egg Sandwiches', 'Challah French Toast (Plain or Raisin)', 'Choose Challah', 1, 1, 50, 'Raisin', NULL, 0.00, 20, false),
    ('Breakfast', 'From the Griddle', 'Buttermilk Pancakes', 'Add Breakfast Meat', 0, 1, 50, 'Ham', 'Ham', 3.00, 10, false),
    ('Breakfast', 'From the Griddle', 'Buttermilk Pancakes', 'Add Breakfast Meat', 0, 1, 50, 'Bacon', 'Bacon', 3.00, 20, false),
    ('Breakfast', 'From the Griddle', 'Buttermilk Pancakes', 'Add Breakfast Meat', 0, 1, 50, 'Sausage', 'Sausage', 3.00, 30, false),
    ('Breakfast', 'From the Griddle', 'Buttermilk Pancakes', 'Add Breakfast Meat', 0, 1, 50, 'Taylor Ham', 'Taylor Ham', 3.00, 40, false),
    ('Breakfast', 'From the Griddle', 'Blueberry Pancakes', 'Add Breakfast Meat', 0, 1, 50, 'Ham', 'Ham', 2.55, 10, false),
    ('Breakfast', 'From the Griddle', 'Blueberry Pancakes', 'Add Breakfast Meat', 0, 1, 50, 'Bacon', 'Bacon', 2.55, 20, false),
    ('Breakfast', 'From the Griddle', 'Blueberry Pancakes', 'Add Breakfast Meat', 0, 1, 50, 'Sausage', 'Sausage', 2.55, 30, false),
    ('Breakfast', 'From the Griddle', 'Blueberry Pancakes', 'Add Breakfast Meat', 0, 1, 50, 'Taylor Ham', 'Taylor Ham', 2.55, 40, false),
    ('Breakfast', 'From the Griddle', 'Blueberry Pancakes', 'Choose Size', 1, 1, 60, 'Full Stack', NULL, 0.00, 10, true),
    ('Breakfast', 'From the Griddle', 'Blueberry Pancakes', 'Choose Size', 1, 1, 60, 'Short Stack', NULL, -2.00, 20, false),
    ('Breakfast', 'From the Griddle', 'Chocolate Chip Pancakes', 'Choose Size', 1, 1, 50, 'Full Stack', NULL, 0.00, 10, true),
    ('Breakfast', 'From the Griddle', 'Chocolate Chip Pancakes', 'Choose Size', 1, 1, 50, 'Short Stack', NULL, -2.55, 20, false),
    ('Breakfast', 'From the Griddle', 'Belgian Waffle', 'Add Strawberries', 0, 1, 50, 'Strawberries', 'Strawberries', 2.00, 10, false),
    ('Drinks & Ice Cream', 'Beverages', 'Fresh Ground Coffee (Regular or Decaf)', 'Choose Coffee', 1, 1, 50, 'Regular', 'Regular Coffee', 0.00, 10, false),
    ('Drinks & Ice Cream', 'Beverages', 'Fresh Ground Coffee (Regular or Decaf)', 'Choose Coffee', 1, 1, 50, 'Decaf', 'Decaf Coffee', 0.00, 20, false),
    ('Drinks & Ice Cream', 'Beverages', 'Milk or Skim Milk — Small', 'Choose Milk', 1, 1, 50, 'Milk', 'Milk', 0.00, 10, false),
    ('Drinks & Ice Cream', 'Beverages', 'Milk or Skim Milk — Small', 'Choose Milk', 1, 1, 50, 'Skim Milk', 'Skim Milk', 0.00, 20, false),
    ('Drinks & Ice Cream', 'Beverages', 'Milk or Skim Milk — Large', 'Choose Milk', 1, 1, 50, 'Milk', 'Milk', 0.00, 10, false),
    ('Drinks & Ice Cream', 'Beverages', 'Milk or Skim Milk — Large', 'Choose Milk', 1, 1, 50, 'Skim Milk', 'Skim Milk', 0.00, 20, false),
    ('Drinks & Ice Cream', 'Beverages', 'Iced Coffee or Iced Decaffeinated', 'Choose Coffee', 1, 1, 50, 'Iced Coffee', 'Regular Coffee', 0.00, 10, false),
    ('Drinks & Ice Cream', 'Beverages', 'Iced Coffee or Iced Decaffeinated', 'Choose Coffee', 1, 1, 50, 'Iced Decaf', 'Decaf Coffee', 0.00, 20, false),
    ('Drinks & Ice Cream', 'Shakes, Sundaes & Ice Cream', 'Dish of Ice Cream (Chocolate, Vanilla or Strawberry)', 'Choose Flavor', 1, 1, 50, 'Chocolate', 'Chocolate', 0.00, 10, false),
    ('Drinks & Ice Cream', 'Shakes, Sundaes & Ice Cream', 'Dish of Ice Cream (Chocolate, Vanilla or Strawberry)', 'Choose Flavor', 1, 1, 50, 'Vanilla', 'Vanilla', 0.00, 20, false),
    ('Drinks & Ice Cream', 'Shakes, Sundaes & Ice Cream', 'Dish of Ice Cream (Chocolate, Vanilla or Strawberry)', 'Choose Flavor', 1, 1, 50, 'Strawberry', 'Strawberry', 0.00, 30, false);

  INSERT INTO menu_choice_groups (
    menu_item_id,
    label,
    min_selections,
    max_selections,
    sort_order
  )
  SELECT DISTINCT
    item.id,
    seed.choice_label,
    seed.min_selections,
    seed.max_selections,
    seed.group_sort_order
  FROM seed_menu_choices seed
  JOIN menu_groups group_record
    ON group_record.name = seed.group_name
  JOIN menu_categories category
    ON category.group_id = group_record.id
   AND category.name = seed.category_name
  JOIN menu_items item
    ON item.category_id = category.id
   AND item.name = seed.item_name
   AND item.is_modifier = false
  ON CONFLICT (menu_item_id, (lower(label))) DO UPDATE
  SET
    min_selections = EXCLUDED.min_selections,
    max_selections = EXCLUDED.max_selections,
    sort_order = EXCLUDED.sort_order,
    is_active = true,
    updated_at = now();

  INSERT INTO menu_choice_options (
    choice_group_id,
    label,
    ingredient_id,
    price_adjustment,
    sort_order,
    is_default
  )
  SELECT
    choice_group.id,
    seed.option_label,
    ingredient.id,
    seed.price_adjustment,
    seed.option_sort_order,
    seed.is_default
  FROM seed_menu_choices seed
  JOIN menu_groups group_record
    ON group_record.name = seed.group_name
  JOIN menu_categories category
    ON category.group_id = group_record.id
   AND category.name = seed.category_name
  JOIN menu_items item
    ON item.category_id = category.id
   AND item.name = seed.item_name
   AND item.is_modifier = false
  JOIN menu_choice_groups choice_group
    ON choice_group.menu_item_id = item.id
   AND lower(choice_group.label) = lower(seed.choice_label)
  LEFT JOIN ingredients ingredient
    ON seed.ingredient_name IS NOT NULL
   AND lower(ingredient.name) = lower(seed.ingredient_name)
  ON CONFLICT (choice_group_id, (lower(label))) DO UPDATE
  SET
    ingredient_id = EXCLUDED.ingredient_id,
    price_adjustment = EXCLUDED.price_adjustment,
    sort_order = EXCLUDED.sort_order,
    is_default = EXCLUDED.is_default,
    is_active = true,
    updated_at = now();

  -- Legacy choice rows were migrated before this canonical ingredient catalog
  -- existed. Link safe exact-name matches now, plus the two unambiguous side
  -- aliases used by the original menu.
  UPDATE menu_choice_options option_record
  SET
    ingredient_id = ingredient.id,
    updated_at = now()
  FROM ingredients ingredient
  WHERE option_record.ingredient_id IS NULL
    AND lower(ingredient.name) = lower(
      CASE lower(option_record.label)
        WHEN 'two vegetables' THEN 'Vegetables'
        WHEN 'side of spaghetti' THEN 'Spaghetti'
        ELSE option_record.label
      END
    );
END;
$$;

SELECT seed_lazy_janes_menu_composition();
